---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/.vuepress/public/assets
  label: Assets
  create: all
  match: "**/*"
- type: document
  path: src/.vuepress/config.js
  label: Config
upload_dir: src/.vuepress/public/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
